[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "4V4Cj43p33eu3fff27HCj1Yf7J9L7Sy7e9fc5vXW3rTC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tuanpm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
